journal_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('journal_entries.urls')),
]

journal_entries/urls.py
from django.urls import path

from . import views

app_name = 'journal_entries'
urlpatterns = [
    # home page
    path('', views.index, name='index'),
    # topics page
    path('topics/', views.topics, name='topics'),
    # individual topic page
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # new topic page
    path('new_topic/', views.new_topic, name='new_topic'),
    # new entry page
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # edit an entry page
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    # includes default auth urls
    path('', include('django.contrib.auth.urls')),
    # registration page
    path('register/', views.register, name='register'),
]

journal_entries/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Topic(models.Model):
    """A topic the user logs"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string respresentation of the model."""
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

journal_entries/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

journal_entries/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.


def index(request):
    # home page
    return render(request, 'journal_entries/index.html')


@login_required
def topics(request):
    # all topics
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')

    context = {'topics': topics}
    return render(request, 'journal_entries/topics.html', context)


@login_required
def topic(request, topic_id):
    # like show in rails
    topic = Topic.objects.get(id=topic_id)
    # checks if topic belongs to current user
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'journal_entries/topic.html', context)


@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('journal_entries:topics')

    context = {'form': form}
    return render(request, 'journal_entries/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('journal_entries:topic', topic_id=topic_id)

    context = {'topic': topic, 'form': form}
    return render(request, 'journal_entries/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('journal_entries:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'journal_entries/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
# Create your views here.


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # logs in user and redirects to home page
            login(request, new_user)
            return redirect('journal_entries:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

journal_entries/templates/journal_entries/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">

  <head>
    <meta charset="uft-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Journal App</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

  </head>
  <body>
      <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a href="{% url 'journal_entries:index' %}" class="navbar-brand">Journal App</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a href="{% url 'journal_entries:topics' %}" class="nav-link">Topics</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item"> 
              <span class="navbar-text">Hello, {{ user.username }}!</span>
            </li> 
            <li class="nav-item">
              <a href="{% url 'users:logout' %}" class="nav-link">Logout</a> 
            </li> 
          {% else %}
            <li class="nav-item">    
              <a href="{% url 'users:register' %}" class="nav-link">Register</a> 
            </li>
            <li class="nav-item">
              <a href="{% url 'users:login' %}" class="nav-link">Log in</a>
            </li>
          {% endif %}
        </ul>
      </div>

      </nav>
      <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
          {% block page_header %}{% endblock page_header %}
        </div>
        <div>
          {% block content %}{% endblock content %}
        </div>
      </main>
  </body>
</html>

journal_entries/templates/journal_entries/edit_entry.html
{% extends "journal_entries/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h3><a href="{% url 'journal_entries:topic' topic.id %}">{{ topic }}</a></h3>

  
{% endblock page_header %}

{% block content %}


  <form action="{% url 'journal_entries:edit_entry' entry.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}
  </form>

{% endblock content %}

journal_entries/templates/journal_entries/index.html
{% extends "journal_entries/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Track your activities and achievements</h1>
  
    <p class="lead">Write about your activities here</p>
    {% if user.is_authenticated %}
    <a href="{% url 'journal_entries:topics' %}" class="btn btn-lg btn-primary" role="button">Enter &raquo;</a>
    {% else %}
    <a href="{% url 'users:register' %}" class="btn btn-lg btn-primary" role="button">Register &raquo;</a>
    {% endif %}
  </div>


{% endblock page_header %}

journal_entries/templates/journal_entries/new_entry.html
{% extends "journal_entries/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h3><a href="{% url 'journal_entries:topic' topic.id %}">{{ topic }}</a></p>

<p>Add a new entry:</p>
{% endblock page_header %}

{% block content %}

<form method='post' action="{% url 'journal_entries:new_entry' topic.id %}" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button name='submit' class="btn btn-primary">Add entry</button>
  {% endbuttons %}
</form>

{% endblock content %}

journal_entries/templates/journal_entries/new_topic.html
{% extends "journal_entries/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <p>Add New Topic:</p>
{% endblock page_header %}

{% block content %}
  
  <form method='post' action="{% url 'journal_entries:new_topic' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add Topic</button>
    {% endbuttons %}
  </form>
  
{% endblock content %}

journal_entries/templates/journal_entries/topic.html
{% extends 'journal_entries/base.html' %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a href="{% url 'journal_entries:new_entry' topic.id %}">Add new entry</a>
  </p>

  {% for entry in entries %}
  <div class="card mb-3">
    <h4 class="card-header">
      {{ entry.date_added|date:'M d, Y H:i' }}
      <small><a href="{% url 'journal_entries:edit_entry' entry.id %}">edit entry</a></small>
    </h4>
    <div class="card-body">
      {{ entry.text|linebreaks }}
    </div>
  </div>
  {% empty %}
    <p>There are no entries for this topic.</p>
  {% endfor %}

{% endblock content %}

journal_entries/templates/journal_entries/topics.html
{% extends "journal_entries/base.html" %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}
{% block content %}
<ul>
  {% for topic in topics %}
    <li><h3>
      <a href="{% url 'journal_entries:topic' topic.id %}">{{ topic }}</a>
    </h3></li>
  {% empty %}
    <li><h3>No topics added yet.</h3></li>
  {% endfor %}

</ul>
<h3><a href="{% url 'journal_entries:new_topic' %}">Add a new topic</a></h3>
{% endblock content %}